name: Awni Hannun
description: Blog 
avatar: https://s.gravatar.com/avatar/952ab78c5d7894a988d7cd403bbf9cf4?s=80
footer-links:
  email:
  github: awni
  twitter: awnihannun
disqus: awni-github-io
google_analytics: UA-104740087-1
url: https://awni.github.io/
baseurl: ""
permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
